version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    image: auth:latest
    ports:
      - "8084:8084"
    depends_on:
      - mongo
    networks:
      - auth-network
      - items_store-network

  mongo:
    image: mongo:latest
    ports:
      - "27019:27019"  # Map container port 27018 to host port 27018
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--port", "27019"]
    networks:
      - auth-network

networks:
  items_store-network:
    external: true
  auth-network:
    driver: bridge

volumes:
  mongo_data: