spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: payments

authentication-service:
  user:
    username: payment@service.com
    password: paymentService
  server:
    host: localhost
    port: 8084

cart-service:
  server:
    host: localhost
    port: 8082

server:
  port: 9191