spring:
  data:
    mongodb:
      host: localhost
      port: 27030
      database: items
  main:
    allow-bean-definition-overriding: true

authentication-service:
  user:
    username: items@service.com
    password: itemsService
  server:
    host: localhost
    port: 8084

items-service:
  server:
    host: localhost
    port: 8081

server:
  port: 9595